server {
    listen 3000;
    listen [::]:3000;
    server_name _;

    root /usr/share/nginx/html;

    rewrite ^/config.json$ /config.json break;
    rewrite ^/manifest.json$ /manifest.json break;

    rewrite ^/sw.js$ /sw.js break;
    rewrite ^/pdf.worker.min.js$ /pdf.worker.min.js break;

    rewrite ^/public/(.*)$ /public/$1 break;
    rewrite ^/assets/(.*)$ /assets/$1 break;

    rewrite ^/element-call/dist/(.*)$ /element-call/dist/$1 break;

    rewrite ^(.+)$ /index.html break;
  
}
